# An Introduction to Pandas

Pandas is a Python library used for data analysis and manipulation. It offers data structures like DataFrames and Series, which are designed to work with structured data, such as tables and time series. It is built upon the NumPy library and is widely used in various fields, including data science, finance, and statistics. 
Pandas enables users to perform tasks such as data cleaning, transformation, merging, and analysis efficiently. Its functionalities include handling missing data, reshaping datasets, and slicing and indexing data. Pandas is often compared to SQL for data extraction and filtering, but Pandas excels at data cleaning, manipulation, and visualization, and it integrates seamlessly with other Python libraries.
The name "Pandas" is derived from "panel data," a term for multi-dimensional structured datasets. It was created by Wes McKinney in 2008 and has since become a fundamental tool in the Python data science ecosystem.

## Basic Pandas Concepts

Some very basic Pandas and python concepts to get started

#### Import the pandas package

In [1]:
import pandas as pd

#### Create a simple DataFrame

- syntax: pd.DataFrame({column1 : value1, column2 : value2, column3 : value3})

You can have anything as column names and anything as values.

The only requirement is to have all value lists being of equal length (all are of length 3 in this example)

There are many ways to create a data frame and you will see some more during the course. All of them can be seen documented [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html).

In [2]:
df = pd.DataFrame({'name':['Bob','Jen','Tim'],
                   'age':[20,30,40],
                   'pet':['cat', 'dog', 'bird']})

df

  name  age   pet
0  Bob   20   cat
1  Jen   30   dog
2  Tim   40  bird

#### View the column names and index values

The index is one of the most important concepts in pandas.

Each dataframe has only a single index which is always available as `df.index` and if you do not supply one (as we did not for this dataframe) a new one is made automatically.

Indexes define how to access rows of the dataframe.

The simplest index is the range index but there are more complex ones like interval index, datetime index and multi index.

We will explore indexes more in depth during the course of this lecture.

In [3]:
print(df.columns)
print(df.index)

Index(['name', 'age', 'pet'], dtype='object')
RangeIndex(start=0, stop=3, step=1)

#### Select a column by name in 2 different ways

These two ways are equivalent and can be used interchangeably almost always.

The primary exception is when the name of the column contains spaces. If for example we had a column called "weekly sales" we have to use df['weekly sales'] because `df.weekly sales` is a syntactic error.

In [4]:
#print(df['name'])
print(df.name)
print(df.age)

0    Bob
1    Jen
2    Tim
Name: name, dtype: object
0    20
1    30
2    40
Name: age, dtype: int64

#### Select multiple columns

To select multiple columns we use `df[columns_to_select]` where `columns_to_select` are the columns we are interested in given as a simple python list. As the result we will get another data frame.

This is the equivalent of listing columns names in `SELECT` part of a sql query.

In [5]:
df[['name','pet']]

  name   pet
0  Bob   cat
1  Jen   dog
2  Tim  bird

#### Select a row by index

Regular selection of rows goes via its index. When using range indices we can access rows using integer indices but this will not work when using datetime index for example.

We can always access any row in the dataframe using `.iloc[i]` for some integer i.

The result is a series object from which we can access values by using column indexing.

In [6]:
df.iloc[0]

name    Bob
age      20
pet     cat
Name: 0, dtype: object

### Sort Function

- pandas.pydata.org
- https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_values.html

#### Sort the data by pet

There are two ways to sort.
- By index
- By value

By value means sorting according to value in a column.

In this example we sort the rows of the dataframe based on values in 'pet' column.

The parameter `ascending = True` means that we want the rows sorted in ascending order. This is the same as sql 'ASC'. To get descending order use `ascending = False`.

`inplace` is very important and you should always remember it. When `inplace=True` the dataframe is modified in place which means that no copies are made and your previous data stored in the dataframe is lost. By default inplace is always False. When it is false a copy is made of your data and that copy is sorted and returned as output.

The output of `sort_values` is always a dataframe returned but the behaviour depends strongly on the `inplace` parameter.

In [7]:
df = pd.DataFrame({'name':['Bob','Jen','Tim'],
                   'age':[20,30,40],
                   'pet':['cat', 'dog', 'bird']})
df1 = df.sort_values('pet',inplace=False, ascending=True)
print(df1)
print("df ")
df

  name  age   pet
2  Tim   40  bird
0  Bob   20   cat
1  Jen   30   dog
df

  name  age   pet
0  Bob   20   cat
1  Jen   30   dog
2  Tim   40  bird

### Indexing with DataFrames

Everything we discussed about indexing in numpy arrays applies to dataframes as well.

DataFrames are very similar to 2d-arrays with the main exception being that in DataFrames you can index using strings (column names).

#### View the index after the sort

In [8]:
df

  name  age   pet
0  Bob   20   cat
1  Jen   30   dog
2  Tim   40  bird

#### Difference between loc and iloc

- `.loc` selection is based on the value of the index. For example if the index was categorical we could index via some category.
- `.iloc` selection is **always** based on integer positions. When using iloc we are treating the dataframe as 2d-array with no special structure compared to the case of `.loc`

In [9]:
df.loc[0] #index based

name    Bob
age      20
pet     cat
Name: 0, dtype: object

In [10]:
df.iloc[0] #relative position based indexing

name    Bob
age      20
pet     cat
Name: 0, dtype: object

#### Use iloc to select all rows of a column

This will select all rows of the second column.

Remember `:` = `::1`

First index is always row and second is always column when dealing with dataframes.

In [11]:
df.iloc[:,2]

0     cat
1     dog
2    bird
Name: pet, dtype: object

#### Use iloc to select the last row

In [12]:
df.iloc[-1,:]

name     Tim
age       40
pet     bird
Name: 2, dtype: object

## Basic Pandas Concept Exercises

In [ ]:
sales = [100,130,119,92,35]
customer_account = ['B100','J101','X102','P103','R104']
city = ['BOS','LA','NYC','SF','CHI']

#### Create a DataFrame with the data above

In [ ]:
data = pd.DataFrame({
    'customer_account': customer_account,
    'city': city,
    'sales': sales
})

data

#### What is the name of the first column?

In [ ]:
data.columns[0]

#### Sort the DataFrame by city in descending order (check the documentation for sort)

#### Which customer is in the last row of the DataFrame?

#### Reorder the columns with customer in the first column

# Basic Pandas Functionality

Before we learn about what Pandas can do, we need to first import some data

## Importing Data

Python allows you to connect to any type of database. To make this easy for newbies, we've create a notebook to help you connect to the Strata Scratch platform and pull data. Use the notebook below to pull data from our database.

[Connect to Strata Scratch with Python](https://colab.research.google.com/drive/1VtywiAAI-ucfTzBa6YDca8k4gfGiEPnn)

### Install the Database Module

The code below installs a postgres database module to allow our notebook to connect to the Strata Scratch database

In [ ]:
!pip install psycopg2

### Import Required Modules

Import a few required modules that enables us to query data and perform analytics

In [ ]:
import numpy as np
import pandas as pd
import psycopg2 as ps

### Connect to Strata Scratch

Make sure to enter your username and database password. Your database password is not the same as your login password. You can find your database password in the Profile tab once logged into Strata Scratch.

In [ ]:
host_name = 'db-strata.stratascratch.com'
dbname = 'db_strata'
port = '5432'
user_name = '' #enter username
pwd = '' #enter your database password found in the profile tab in Strata Scratch

try:
    conn = ps.connect(host=host_name,database=dbname,user=user_name,password=pwd,port=port)
except ps.OperationalError as e:
    raise e
else:
    print('Connected!')

### Pull the Titanic Dataset From Strata Scratch

#### Enter SQL code below to pull the dataset you're interested in

If you get an error, it likely means that the connection timed out. Try connecting to Strata Scratch again before executing the code below.

A list of datasets is found in SQL LAB in Strata Scratch.

In [ ]:
#Write SQL below to pull datasets
cur = conn.cursor()
cur.execute("""
            SELECT *  FROM titanic;
            """)
data = cur.fetchall()
colnames = [desc[0] for desc in cur.description]
conn.commit()

#create the pandas dataframe
data = pd.DataFrame(data)
data.columns = colnames

#close the connection
cur.close()

#### Check To See If Your Pulled The Dataset

The Titanic dataset should be in a pandas dataframe named `data`

In [ ]:
data.head()

## Basic Pandas Functionality

Now that we imported some data, let's take a look at what Pandas can do

#### Investigate the first few rows of data

The `head` method by default prints the first 5 rows of your dataframe.

If you pass it a parameter `n` it will print first `n` rows.

The docs are [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.head.html)

In [ ]:
data.head()

#### Investigate the last 10 rows of data

tail is similar to head except it prints the last `n` rows.

In [ ]:
data.tail(10)

#### Investigate the data types in the DataFrame

This method will tell you the types of columns.

Types are automatically inferred by pandas and usually you do not have to worry about them.

[docs](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.info.html)

In [ ]:
data.info()

#### Get some summary statistics

To learn more about describe visit [this link](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.describe.html)

In [ ]:
data.describe().T

### Filtering Dataframes

You can filter data based on the columns and values in the dataframe

#### Filter the data for men

There are two pieces of the puzzle here:
- `data.sex=='male'` will give a boolean array where True means that row has a column called sex which has value 'male'. This numpy array is called the predicate.
- data[data.sex=='male'] will give back all rows for which the predicate holds true.

The result of this filter is a dataframe with same columns as the input dataframe.

In [ ]:
data[data.sex=='male']

#### Filter the ages for the men

Again there are two important parts:
- `data.sex=='male'` is the predicate as before
- `data.age` means taking the values for the age column, and `data.age[data.sex=='male']` means taking all ages which are related to male rows.

The result of this is pandas series **not** a dataframe.

In [ ]:
data.age[data.sex=='male']

### Adding methods to filters

A method is a function and is used frequently when analyzing data in Pandas. There are countless Pandas methods. We'll go over a few of the basic ones to show how you can use methods to quickly analyze your data.

#### How many men and women were on the Titanic?

The pipeline always goes the same way
- Predicate is evalatued
- Data is filtered according to a predicate
- An aggregate value is computed after the filtering.

The count method simply counts the number of frames in the dataframe.

In [ ]:
data.sex[data.sex=='male'].count()

In [ ]:
data.sex[data.sex=='female'].count()

#### What was the survival rate for adult men (age>=18)

Here we combine predicates using the and operator (&).

This operator applies the logical and operation between elements at matching positions.

For example:
- x = np.array([True, False, True, True])
- y = np.array([False, True, False, True])
- will give x & y = np.array([True & False, False & True, True & False, True & True]).

In the following example we use the or combiner (|).

You can combine any two boolean numpy arrays as long as they have the same shape using the & and | operators.

Combining regular python lists this way does not work.

In [ ]:
data.survived[(data.sex=='male')&(data.age>=18)].mean()

#### What was the survival rate for women and children?

The mean method is the same as AVERAGE in SQL.

In [ ]:
data.survived[(data.sex=='female')|(data.age<18)].mean()

#### Use groupby to compare the survival rates of men and women

The `groupby` method is one of the most important tools you will use in your day to day work.

It's main input parameter is either a string denoting a column name or a list of strings denoting a list of column names.

It's output is a GroupBy object which is very similar to a dataframe.

The operation of groupby is the same as SQL GROUPBY.

For more info see the [docs](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.groupby.html).

In [ ]:
data.groupby('sex')['survived'].mean()

#### Create a DataFrame with groupby

In [ ]:
new = data.groupby(['sex','pclass'])['survived','age'].mean()
new

## Importing and Exporting Data with Pandas

#### Pandas has easy to use functions for importing and exporting different data types:
- CSV Files
- Excel Worksheets
- Queries from Databases

Strata Scratch notebooks will exclusively be import data from our platform so we will not be covering other import techniques.

## More Basic Pandas Exercises

#### What was the average age of the survivors?

#### What was the combined survival rate of both children (age less than 18) and seniors (age greater than 60)?

#### Group by pClass and investigate average survival rate, age and fare

#### Create a CSV with the names and ages of the surivors and another CSV file with the names and ages of the deceased. Please refer to documention (to_csv method) to complete the exercise.

[Documentation for the method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html)